export const getKpiCardsData = (kpiData, year, theme) => [
  {
    title: "Emisiones Totales GHG",
    value: `${kpiData.totalEmissions.value.toLocaleString()} tCO₂e`,
    change: kpiData.totalEmissions.change,
    changeText: `${kpiData.totalEmissions.change > 0 ? "+" : ""}${kpiData.totalEmissions.change}% vs ${year - 1}`,
    changeValue: `${kpiData.totalEmissions.changeValue > 0 ? "+" : ""}${kpiData.totalEmissions.changeValue.toLocaleString()} tCO₂e`,
    isPositive: kpiData.totalEmissions.isPositive,
    icon: "chart",
    color: theme.colors.ghg.primary,
  },
  {
    title: "Scope 1 (Directo)",
    value: `${kpiData.scope1.value.toLocaleString()} tCO₂e`,
    change: kpiData.scope1.change,
    changeText: `${kpiData.scope1.change > 0 ? "+" : ""}${kpiData.scope1.change}% vs ${year - 1}`,
    changeValue: `${kpiData.scope1.changeValue > 0 ? "+" : ""}${kpiData.scope1.changeValue.toLocaleString()} tCO₂e`,
    isPositive: kpiData.scope1.isPositive,
    icon: "factory",
    color: "#D32F2F",
  },
  {
    title: "Scope 2 (Indirecto)",
    value: `${kpiData.scope2.value.toLocaleString()} tCO₂e`,
    change: kpiData.scope2.change,
    changeText: `${kpiData.scope2.change > 0 ? "+" : ""}${kpiData.scope2.change}% vs ${year - 1}`,
    changeValue: `${kpiData.scope2.changeValue > 0 ? "+" : ""}${kpiData.scope2.changeValue.toLocaleString()} tCO₂e`,
    isPositive: kpiData.scope2.isPositive,
    icon: "zap",
    color: "#FFA000",
  },
  {
    title: "Scope 3 (Cadena)",
    value: `${kpiData.scope3.value.toLocaleString()} tCO₂e`,
    change: kpiData.scope3.change,
    changeText: `${kpiData.scope3.change > 0 ? "+" : ""}${kpiData.scope3.change}% vs ${year - 1}`,
    changeValue: `${kpiData.scope3.changeValue > 0 ? "+" : ""}${kpiData.scope3.changeValue.toLocaleString()} tCO₂e`,
    isPositive: kpiData.scope3.isPositive,
    icon: "truck",
    color: "#7B1FA2",
  },
];